/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hemanth
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton7.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jComboBox1.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO ADMIN PORTAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 37, -1, 32));

        jButton1.setBackground(new java.awt.Color(51, 0, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("MANAGE USERS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 203, 369, 42));

        jButton2.setBackground(new java.awt.Color(51, 0, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("MANAGE FOOD DATABASE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 349, 369, 42));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 0));
        jButton3.setText("LIST ALL USERS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 411, 258, 33));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 255, 0));
        jButton4.setText("SEARCH USER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 260, 33));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 255, 0));
        jButton5.setText("DELETE USER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 341, 260, 33));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 255, 0));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 551, 120, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 364, 10));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 270, 33));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 251, 180, 23));

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 255, 0));
        jButton7.setText("View");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 130, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 170, 23));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 270, 33));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 270, 33));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 160, 23));

        jComboBox1.setBackground(new java.awt.Color(0, 102, 102));
        jComboBox1.setForeground(new java.awt.Color(0, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select type--", "vegetables-and-fruits", "snacks", "non-veg" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton1.getText().equalsIgnoreCase("Manage users")){
        jButton4.setText("Search user");
        jButton5.setText("Delete user");
        jButton3.setText("List users");
        }
        jButton3.setVisible(!false);
        jButton4.setVisible(!false);
        jButton5.setVisible(!false);
        jButton2.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton4.setText("ADD FOOD");
        jButton5.setText("UPDATE FOOD");
        jButton3.setText("DELETE FOOD");
        jButton2.setVisible(false);
        jButton1.setText(jButton2.getText());
        jButton3.setVisible(!false);
        jButton4.setVisible(!false);
        jButton5.setVisible(!false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jButton5.isVisible()||jButton4.isVisible()||jButton3.isVisible()){
        jButton1.setText("Manage users");
        jButton2.setText("Manage food database");
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton2.setVisible(true);
        jLabel2.setVisible(false);
        jTextField1.setVisible(false);
        jButton7.setVisible(false);
         jTextField2.setVisible(!true);
        jTextField3.setVisible(!true);
        jLabel3.setVisible(!true);
        jLabel4.setVisible(!true);
        jComboBox1.setVisible(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
        }else {
            new starting().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jButton4.getText().equalsIgnoreCase("search user")){
        jLabel2.setVisible(true);
        jTextField1.setVisible(true);
        jButton7.setVisible(true);
        jButton3.setVisible(false);
        jButton5.setVisible(false);
        jButton7.setText("View");
        }else{
           jLabel2.setVisible(true);
        jTextField1.setVisible(true);
        jButton7.setVisible(true);
        jButton3.setVisible(false);
        jButton5.setVisible(false);
        jButton7.setText("Add");
        jLabel2.setText("Food Name");
        jLabel3.setText("Amount");
        jLabel4.setText("Calories");
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jComboBox1.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(jButton7.getText().equals("View")){
        Profile p=new Profile(jTextField1.getText(),"admin");
        if(!p.jTextField5.getText().equals("")){
        p.jRadioButton1.setVisible(false);
        p.head.setVisible(false);
        p.setVisible(true);
        }
        }
        else if(jButton7.getText().equals("Delete")){
           
             try{
       String url="jdbc:mysql://127.0.0.1:3306/caloricator?zeroDateTimeBehavior=convertToNull";
           Class.forName("com.mysql.jdbc.Driver");
                 Connection con = (Connection) DriverManager.getConnection(url, "root", "");
           Statement st=con.createStatement();
           int c=0;
           c+=st.executeUpdate("delete from habits where userid='"+jTextField1.getText()+"'");
           c+=st.executeUpdate("delete from history where Email='"+jTextField1.getText()+"'");
           c+=st.executeUpdate("delete from Login where Email='"+jTextField1.getText()+"'");
           c+=st.executeUpdate("delete from tracker where userid='"+jTextField1.getText()+"'");
           c+=st.executeUpdate("delete from user where Email='"+jTextField1.getText()+"'");
           if(c!=0){
          JOptionPane.showMessageDialog(this,"successfully Deleted", "success",  JOptionPane.PLAIN_MESSAGE);
           }else
           {
              JOptionPane.showMessageDialog(this,"No users deleted", "Failure",  JOptionPane.ERROR_MESSAGE); 
           }
           con.close();
        }   catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(jButton7.getText().equals("Add")){
             if(jComboBox1.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this,"Select valid food type", "Failure",  JOptionPane.ERROR_MESSAGE);
            }else{
      if(!(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jTextField3.getText().isEmpty())){
        addup(0);
        JOptionPane.showMessageDialog(this,"successfully added", "Failure",  JOptionPane.PLAIN_MESSAGE);
        }else{
          JOptionPane.showMessageDialog(this,"one or more field is empty", "Failure",  JOptionPane.ERROR_MESSAGE);
      }
             }
    }else if(jButton7.getText().equals("update")){
        if(jComboBox1.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this,"Select valid food type", "Failure",  JOptionPane.ERROR_MESSAGE);
            }else{
      if(!(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jTextField3.getText().isEmpty())){
        int a=addup(1);
        if(a==1){
        JOptionPane.showMessageDialog(this,"successfully updated", "Failure",  JOptionPane.PLAIN_MESSAGE);
        
        }}else{
          JOptionPane.showMessageDialog(this,"one or more field is empty", "Failure",  JOptionPane.ERROR_MESSAGE);
      }
    }
    }else if(jButton7.getText().equalsIgnoreCase("delete food")){
        int x=addup(2);
        if(x==1){
        JOptionPane.showMessageDialog(this,"successfully deleted", "Failure",  JOptionPane.PLAIN_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton7ActionPerformed
private int addup(int x){
     try{
           String url="jdbc:mysql://127.0.0.1:3306/caloricator?zeroDateTimeBehavior=convertToNull";
           Class.forName("com.mysql.jdbc.Driver");
                 Connection con = (Connection) DriverManager.getConnection(url, "root", "");
           Statement st=con.createStatement();
           String tab = (String) jComboBox1.getSelectedItem();
           ResultSet rs = st.executeQuery("SELECT MAX(id) FROM `"+tab+"`");
           rs.next();
           int n=rs.getInt(1);
           float am = 0,ca = 0;if(x<2){
           am=Float.parseFloat(jTextField2.getText());
           ca=Float.parseFloat(jTextField3.getText());
           }
         switch (x) {
             case 0:
                 st.executeUpdate("INSERT INTO `"+tab+"`(`id`, `name`, `amount`, `calories`) VALUES ('"+(n+1)+"','"+jTextField1.getText()+"','"+am+"','"+ca+"')");
                 break;
             case 1:
                 int z=st.executeUpdate("UPDATE `"+tab+"` SET `amount`='"+am+"',`calories`='"+ca+"' WHERE `name`='"+jTextField1.getText()+"'");
                 if(z<1){
                     JOptionPane.showMessageDialog(this,"No entry found", "Failure",  JOptionPane.ERROR_MESSAGE);
                     return 0;
                 }
                 break;
             default:
                 
                int a= st.executeUpdate("DELETE FROM `"+tab+"` WHERE `name` = '"+jTextField1.getText()+"'");
                if(a<1){
                JOptionPane.showMessageDialog(this,"No entry found", "Failure",  JOptionPane.ERROR_MESSAGE);
            return 0;
                }
                 break;
         }
           con.close();
            }
           catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
     return 1;
    
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jButton5.getText().equalsIgnoreCase("delete user")){
        jLabel2.setVisible(true);
        jTextField1.setVisible(true);
        jButton7.setVisible(true);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton7.setText("Delete");
        jTextField1.setText("");
        }else if(jButton5.getText().equalsIgnoreCase("update food")){
            jLabel2.setVisible(true);
        jTextField1.setVisible(true);
        jButton7.setVisible(true);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton7.setText("Delete");
        jTextField1.setText("");
            jLabel2.setText("Food Name");
        jLabel3.setText("Amount");
        jLabel4.setText("Calories");
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jButton7.setText("update");
        jComboBox1.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jButton3.getText().equalsIgnoreCase("List users")){
            new list().setVisible(true);
        }else if(jButton3.getText().equalsIgnoreCase("delete food")){
            jLabel2.setText("Food Name");
            jLabel2.setVisible(true);
            jTextField1.setVisible(true);
            jButton7.setVisible(true);
            jButton7.setText("delete food");
            jComboBox1.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
